name: Main Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'   # Only if src directory files changed
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'   # Only if src directory files changed

jobs:
  version-and-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Prevents this job from running in PR. It will only run on push to main.
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9
        with:
          versionSpec: '5.x'

      - name: Generate Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9

      - name: Tag and Push Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag $(echo ${{ steps.gitversion.outputs.semver }})
          git push origin $(echo ${{ steps.gitversion.outputs.semver }})

  build-image:
    runs-on: ubuntu-latest
    needs: version-and-tag
    if: github.event_name == 'push' # Prevents this job from running in PR. It will only run on push to main.
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Get Version from Git
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Install dependencies
        run: |
          cd src
          go mod tidy

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Tag Docker Image
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker build -t nlipatov/cinemator:${VERSION} src
          docker tag nlipatov/cinemator:${VERSION} nlipatov/cinemator:latest

      - name: Push Docker Images
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker push nlipatov/cinemator:${VERSION}
          docker push nlipatov/cinemator:latest